#!/usr/bin/env bash
# conflict-scan.sh [--watch] [pr...]: test-merge every approved PR (open, base trunk, labelled
# $APPROVED_LABEL) against trunk and against every PR in the merge queue, which lands first.
#   CONFLICT vs trunk, generated files only  → fixed: trunk merged in, files regenerated, normal push
#   CONFLICT vs trunk, any source file       → reported; a change request, or a resolver agent on the owner's say
#   AHEAD #Q                                 → will conflict once #Q lands; --watch fixes it then if generated
# A generated file is pnpm-lock.yaml, or one whose first lines say "Generated by `pnpm <script>`"
# (the script runs in the file's nearest package). --watch rescans each time trunk or the approved set
# moves, for up to $WATCH_MINUTES (default 110). PRs untouched for $MAX_AGE_DAYS (default 7) are skipped.
set -u
S=$(cd "$(dirname "$0")" && pwd); . "$S/_stack-env.sh"; ensure_wt
APPROVED_LABEL=${APPROVED_LABEL:-Release Authorised}
watch=0; [ "${1:-}" = --watch ] && { watch=1; shift; }
owner=${R%/*}; name=${R#*/}

approved() {
  [ $# -gt 0 ] && { echo "$@"; return; }
  gh pr list --repo "$R" --state open --base "$trunk" --label "$APPROVED_LABEL" --limit 100 \
    --search "updated:>=$(date -u -v-"${MAX_AGE_DAYS:-7}"d +%F 2>/dev/null || date -u -d "-${MAX_AGE_DAYS:-7} days" +%F)" \
    --json number --jq '.[].number' | tr '\n' ' '
}
queued() {
  gh api graphql -f query="{repository(owner:\"$owner\",name:\"$name\"){mergeQueue(branch:\"$trunk\"){entries(first:50){nodes{pullRequest{number headRefName}}}}}}" \
    --jq '.data.repository.mergeQueue.entries.nodes[].pullRequest|"\(.number) \(.headRefName)"' 2>/dev/null
}
# conflicts <ours-ref> <theirs-ref>: conflicted paths, empty when the merge is clean
conflicts() { git merge-tree --write-tree --name-only "$1" "$2" 2>/dev/null | sed -n '2,/^$/p' | grep .; }
gen_cmd() {  # gen_cmd <ref> <path>: "<dir>\t<command>" when <path> is generated, else nothing
  local ref=$1 f=$2 d s
  [ "$(basename "$f")" = pnpm-lock.yaml ] && { printf '.\tpnpm install --lockfile-only\n'; return; }
  s=$(git show "$ref:$f" 2>/dev/null | head -3 | sed -nE 's/.*Generated by `pnpm ([a-zA-Z0-9:_-]+)`.*/\1/p' | head -1)
  [ -z "$s" ] && return
  d=$(dirname "$f"); while [ "$d" != . ] && ! git cat-file -e "$ref:$d/package.json" 2>/dev/null; do d=$(dirname "$d"); done
  printf '%s\tpnpm %s\n' "$d" "$s"
}
fix_generated() {  # fix_generated <pr> <branch> <files...>: exit 0 only when fixed and pushed
  local p=$1 b=$2; shift 2
  local f g cmds=""
  for f in "$@"; do g=$(gen_cmd "origin/$b" "$f"); [ -z "$g" ] && return 1; cmds="$cmds$g"$'\n'; done
  git merge --abort 2>/dev/null; git checkout -q --detach "origin/$b" >>"$QUIET" 2>&1
  git merge --no-edit -q "origin/$trunk" -m "Merge $trunk into $b" >>"$QUIET" 2>&1
  printf '%s' "$cmds" | sort -u | while IFS=$'\t' read -r d g; do [ -n "$d" ] && (cd "$d" && $g >>"$QUIET" 2>&1); done
  git add -- "$@"
  [ -n "$(git diff --name-only --diff-filter=U)" ] || grep -qs '^<<<<<<<' -- "$@" && { git merge --abort; return 1; }
  git commit -q --no-edit >>"$QUIET" 2>&1 && git push -q origin "HEAD:refs/heads/$b" >>"$QUIET" 2>&1
}

scan() {
  cd "$WT"; local list q p b c
  list=$(approved "$@"); q=$(queued)
  git fetch -q origin "$trunk" $(echo "$q" | awk '{print $2}') 2>/dev/null
  for p in $list; do
    b=$(gh pr view "$p" --repo "$R" --json headRefName --jq .headRefName); git fetch -q origin "$b" 2>/dev/null
    c=$(conflicts "origin/$b" "origin/$trunk")
    if [ -n "$c" ]; then
      if fix_generated "$p" "$b" $c; then echo "FIXED #$p: regenerated $(echo $c)"
      else echo "CONFLICT #$p vs $trunk: $(echo $c)"; fi
      continue
    fi
    while read -r qp qb; do
      [ -z "$qp" ] || [ "$qp" = "$p" ] && continue
      c=$(conflicts "origin/$b" "origin/$qb"); [ -n "$c" ] && echo "AHEAD #$p will conflict once #$qp lands: $(echo $c)"
    done <<< "$q"
  done
  echo "SCANNED $(date -u +%H:%M) trunk=$(git rev-parse --short "origin/$trunk") prs: $list"
}

[ $watch = 0 ] && { scan "$@"; exit 0; }
last=""
for i in $(seq 1 "${WATCH_MINUTES:-110}"); do
  key="$(git -C "$WT" ls-remote -q origin "refs/heads/$trunk" | cut -c1-12) $(approved "$@")"
  [ "$key" != "$last" ] && { scan "$@"; last=$key; }
  sleep 60
done
